from typing import Literal
import numpy

class Cnf:
    def __new__(
        cls,
        num_variables: int,
        num_literals: int,
        num_clauses: int,
        seed: int,
        algorithm: Literal["chacha8", "pcg64"],
        are_distinct: bool,
    ) -> Cnf: ...
    def to_dimacs_string(self) -> str: ...
    @property
    def num_variables(self) -> int: ...
    @property
    def num_literals(self) -> int: ...
    @property
    def num_clauses(self) -> int: ...
    @property
    def seed(self) -> int: ...
    @property
    def algorithm(self) -> Literal["chacha8", "pcg64"]: ...
    def to_formula(self) -> numpy.ndarray: ...
