from ..solvers import kissat as kissat, fixstars as fixstars

class SolverOutput:
    def to_csv_record(self) -> str: ...
    @property
    def is_satisfiable(self) -> bool: ...
    @property
    def process_time(self) -> float: ...
    @property
    def errors(self) -> list[str]: ...
